### ISSUE TITLE
Variable c may not be defined

### ISSUE THREAD

**Issue by zzzyzh** [mazurowski-lab/segment-anything-medical-evaluation#1]
`c = [int(ci) for ci in c]`

On line 433 of the code, the variable c you are using here does not seem to be defined before it is used, do you know what c means here?

Also, if your code can only split one mask at a time?

Thank you for your kindness.

**Comment by haoyudong-97** [comment]
Thanks for pointing out. We have moved the visualization to a separate file in our current version, so I didn't catch the bug. "c" means the point coordinates and should be "pc" in this case.

By one mask do you mean one type of mask in the multi-class setting? If so, the code can either treat multi-class masks as binary or predict the mask for a single type because SAM can only output binary predictions.

**Comment by zzzyzh** [comment]
Thanks a lot, I find it!
And when will you update the code on GitHub?

**Comment by haoyudong-97** [comment]
Great! We are aiming for releasing the new code by later this week.

**Comment by zzzyzh** [comment]
How should I display the SAM generated mask on the image? Has this section been updated in subsequent code, please?

**Comment by zzzyzh** [comment]
Is it very common to have split tasks with multiple tabs? Do you have an implementation of multi-tab splitting in the next version of the code?

**Comment by haoyudong-97** [comment]
I didn't get your question. What do you mean by "multiple tabs"?

**Comment by zzzyzh** [comment]
Sorry for my mistake. I mean do you have an implementation of verifying multi class?
